Make heat pump type a selection item in config flow
CJNE/thermiagenesis pull request #234
Opened 2023-10-26 14:34 UTC by mairas

This PR has two minor changes. If you'd prefer two separate PRs instead, I'm happy to do that as well!

First, the translation files present in the component cause issues at least when the English language UI is used (lots of translation errors instead of intended strings). Since the translation files don't really do anything at the moment, I removed them altogether.

Second, in the initial config flow, the heat pump type (inverter vs mega) is now a selection item (radio buttons) instead of a free-form string field.

2023-10-27 14:29 UTC, josbmw commented
Thanks Mairas.

Can I easyily upgrade my current configuration based on CNJE without loosing any settings?

2023-10-31 08:46 UTC, mairas commented
> Thanks Mairas.
> 
> Can I easyily upgrade my current configuration based on CNJE without loosing any settings?

Yes, this has no impact on the settings schema.

2023-11-05 11:09 UTC, josbmw commented
Just updated HA to 2023.11.1.
Issues with this plugin:

Logger: homeassistant.setup
Source: setup.py:359 
First occurred: 11:58:00 (1 occurrences) 
Last logged: 11:58:00

Unable to prepare setup for platform thermiagenesis.climate: Platform not found (No module named 'homeassistant.util.temperature').


Any ideas?

2023-11-05 11:21 UTC, josbmw commented
Restored back to 2023.10.5.
Everything back as it should.

2023-11-05 18:06 UTC, mairas commented
Works for me. And definitely unrelated to this PR, in any case. If you think it's an actual code problem, please open a new issue for that.

2023-12-02 15:24 UTC, CJNE requested changes
Thank you for the contribution, very nice!
Instead of deleting the translation files it would be better to fix them so that translations will actually work.
I can take a look at that, so take out the removal of the translation files and then we can merge the other change :)

2023-12-02 15:30 UTC, mairas commented
> Thank you for the contribution, very nice! Instead of deleting the translation files it would be better to fix them so that translations will actually work. I can take a look at that, so take out the removal of the translation files and then we can merge the other change :)

Sure thing! Couldn't figure out that myself. :-D

I removed that commit, it's all yours!

2024-02-28 17:54 UTC, CJNE approved these changes
Nice!

2024-02-28 22:01 UTC, merged

2024-12-08 23:57 UTC, jinnatar commented
Did the translation fixes actually happen anywhere? Because it seems they didn't and the integration name is still just one very long translation error message.